# Generated by Django 5.1.3 on 2025-01-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.TextField()),
                ('brand', models.TextField()),
                ('Year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('fueltype', models.TextField()),
                ('Transmissiontype', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='rest_images')),
            ],
        ),
    ]
