# Generated by Django 5.1.5 on 2025-01-20 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_cardetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetails',
            name='Transmissiontype',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='Year',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='id',
        ),
        migrations.AddField(
            model_name='cardetails',
            name='dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='rent_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='transmissiontype',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
