# Generated by Django 5.1.5 on 2025-01-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_remove_cardetails_transmissiontype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='transmissiontype',
            field=models.TextField(),
        ),
    ]
