# Generated by Django 5.1.5 on 2025-01-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_alter_cardetails_transmissiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='transmissiontype',
            field=models.TextField(null=True),
        ),
    ]
