# Generated by Django 5.1.5 on 2025-01-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_alter_cardetails_transmissiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images'),
        ),
    ]
