# Generated by Django 5.1.5 on 2025-01-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_rename_image_cardetails_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='transmissiontype',
            field=models.TextField(),
        ),
    ]
