# Generated by Django 5.1.5 on 2025-01-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_alter_cardetails_transmissiontype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardetails',
            old_name='images',
            new_name='image',
        ),
    ]
