# Generated by Django 5.1.5 on 2025-01-21 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0011_rentedcars'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='rentedbikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_hours', models.PositiveIntegerField()),
                ('rent_date', models.DateTimeField(auto_now_add=True)),
                ('id_proof', models.ImageField(upload_to='id_proofs/')),
                ('rent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='homeapp.bikedetails')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
