# Generated by Django 5.1.5 on 2025-01-22 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0015_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='rent_hours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.rentedcars'),
        ),
    ]
